### ISSUE TITLE
Add instructions above run statcheck button

### ISSUE THREAD

**Issue by WillemSleegers** [WillemSleegers/statcheck-word#12]
Add instructions just above the run statcheck button to make it clearer what users need to do.

**Comment by MicheleNuijten** [comment]
Tried something here: b30b2e6413f2dc2df7f33865e540ac465bda7940

**Comment by WillemSleegers** [comment]
Alright. Should we keep the instructions text after the user clicks on the Run statcheck button? Perhaps change it to a different text?

**Comment by MicheleNuijten** [comment]
Maybe we could add additional instruction above the "Run again" button? Something like:

"Did you change anything in your statistical results? Run statcheck again to see if there are any inconsistencies left."

**Comment by WillemSleegers** [comment]
The problem I have with instructions is that they will end up annoying me after the first time using the app.

**Comment by WillemSleegers** [comment]
And I'd like there to be as little text as possible.

**Comment by WillemSleegers** [comment]
Added a tooltip right next to the run statcheck button.
