### ISSUE TITLE
Add more detail to text when you click on a detected test

### ISSUE THREAD

**Issue by MicheleNuijten** [WillemSleegers/statcheck-word#17]
For an inconsistent stat: an extra line stating something like "this p-value is not consistent with the reported test stat & df". This may help interpreting the results.

**Comment by MicheleNuijten** [comment]
I didn't know how to get the app to display different messages depending on whether the result was consistent or not. But I had messages like this in mind:

When test = inconsistent, something like:

It seems that the reported _p_-value is inconsistent with its test statistic and degrees of freedom. 
Statcheck computed **p = 0.036**.

When test = consistent, something like this:
This statistical test is internally consistent. 
Statcheck computed **p = .036**.

**Comment by WillemSleegers** [comment]
Added it. =)
