### ISSUE TITLE
Close FAQ element when opening another

### ISSUE THREAD

**Issue by MicheleNuijten** [WillemSleegers/statcheck-word#23]
I think a FAQ text box should close as soon as you open another question. Otherwise the list of FAQs becomes confusing. I think it would be easier if you can always see the list of questions in one glance.

**Comment by WillemSleegers** [comment]
Yup, agreed. We should also see if we can answer each question more succinctly.

**Comment by MicheleNuijten** [comment]
Maybe change this back?

**Comment by WillemSleegers** [comment]
I created a FAQ branch that has the accordion implementation. I like it.
