### ISSUE TITLE
Polish documentation

### ISSUE THREAD

**Issue by WillemSleegers** [WillemSleegers/statcheck-word#4]
Update the documentation, such as adding some brief descriptions to the additional information links, maybe combine the example with the 2nd FAQ question, and so on.

Documentation todo list:

- [x] Improve text visibility in Who to contact question in the FAQ
- [x] Go over the FAQ answers for final confirmation (maybe try to make the answers shorter?)
- [x] Confirm Cite Us text
- [x] Confirm help popovers

**Comment by WillemSleegers** [comment]
What about using something like this for the FAQ? https://themes.gohugo.io/theme/hugo-faq-theme/

**Comment by MicheleNuijten** [comment]
Yes! I like it

**Comment by MicheleNuijten** [comment]
Next meeting: check if FAQ is short enough

**Comment by MicheleNuijten** [comment]
Print 'statcheck' in bold face

**Comment by MicheleNuijten** [comment]
Does statcheck in bold look good?
