### ISSUE TITLE
Add a tag line under the main logo

### ISSUE THREAD

**Issue by WillemSleegers** [WillemSleegers/statcheck-word#7]
Add a tag line such as "A spellchecker for statistics" under the logo to help clarify what the app does.

**Comment by WillemSleegers** [comment]
Added one.

**Comment by WillemSleegers** [comment]
Improve the looks of it.

**Comment by WillemSleegers** [comment]
Maybe change the font to the Microsoft one?

**Comment by MicheleNuijten** [comment]
don't know how to change the font, so I added you to help :D

**Comment by WillemSleegers** [comment]
I set the font family of html and body to "Segoe WP", "Segoe UI", "Arial", sans-serif;.
